# We want install apache2 and php on slave machine using ansible

- name: ansible and php installation
  become: true
  hosts: php-server
  tasks:

    - name: update and upgrade php server
      command: apt update

    - name: upgrade php server
      command: apt upgrade -y

    - name: install apache2 on php swerver
      command: apt install apache2 -y

    - name: start apache2 web server
      service:
        name: apache2
        enabled: yes
        state: started

    - name: set timezone on php server to Africa/Lagos timezone
      command: timedatectl set-timezone Africa/Lagos

    - name: gret php requisitory
      command: apt install apt-transport-https lsb-release software-properties-common ca-certificates -y

    - name: php apt repository
      command: add-apt-repository ppa:ondrej/php -y

    - name: install php
      command: apt install php7.4 -y
